//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int CodigoReserva { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public int Galones { get; set; }
        public Nullable<int> CodigoPago { get; set; }
        public int CodigoEstadoReserva { get; set; }
        public System.DateTime i_fechaCreacion { get; set; }
        public string i_creadoPor { get; set; }
        public int CodigoCliente { get; set; }
        public int CodigoVehiculo { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual EstadoReserva EstadoReserva { get; set; }
        public virtual Pago Pago { get; set; }
        public virtual Vehiculo Vehiculo { get; set; }
    }
}
