//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehiculo()
        {
            this.Disponibilidad = new HashSet<Disponibilidad>();
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int CodigoVehiculo { get; set; }
        public string Color { get; set; }
        public int Anio { get; set; }
        public string TipoCombustible { get; set; }
        public decimal Precio { get; set; }
        public int Capacidad { get; set; }
        public string Placa { get; set; }
        public int CodigoTipoVehiculo { get; set; }
        public int CodigoModelo { get; set; }
        public string ImagenVehiculo { get; set; }
        public string i_creadoPor { get; set; }
        public string i_modificadoPor { get; set; }
        public System.DateTime i_fechaCreacion { get; set; }
        public System.DateTime i_fechaModificado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disponibilidad> Disponibilidad { get; set; }
        public virtual Modelo Modelo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
        public virtual Tipovehiculo Tipovehiculo { get; set; }
    }
}
